### ISSUE TITLE
Rutyna dla SCT_6010

### ISSUE THREAD

**Issue by outlander-modder** [CarnageMarkus/TheDamnedAssets_MOD#3]
SCT_6010 (nowicjusz) nie ma przyznanego miejsca w świecie. Jest to zwykły ambient. Można mu stworzyć jakieś miejsce w twierdzy lub po prostu nie dodawać. Zdecyduj i napisz komentarz/zamknij issue.

**Comment by Castigavi** [comment]
Jeżeli nie jest w żaden sposób istotny to ja bym go nie dodawał.
