### ISSUE TITLE
Nudle

### ISSUE THREAD

**Issue by outlander-modder** [CarnageMarkus/TheDamnedAssets_MOD#5]
Trzeba dodać nudle do świata:
nudes1 (instancja itemu) - skrzynia w bibliotece magów wody
nudes2 - chata krzykacza
nudes3 - jaskinia gilberta
nudes4 - twierdza - pokój tyona
nudes5 - twierdza - biblioteka w której jest lester
nudes6 - obóz łowców - gdzieś koło łóżek
nudes7 - chata cor kaloma
nudes8 - w pobliżu baal cadara

**Comment by Castigavi** [comment]
Dodane.
